package com.zaxxer.hikari.pool;

import java.sql.Statement;

public final class HikariProxyPreparedStatement {
    private final com.mysql.cj.jdbc.ClientPreparedStatement delegate;
    private final String sql;

    public HikariProxyPreparedStatement(String sql) {
        this.sql = sql;
        this.delegate = new com.mysql.cj.jdbc.ClientPreparedStatement(sql);
    }

    public String getPreparedSql() { return sql; }

    public void setString(int index, String value) {
        delegate.setString(index, value);
    }

    public int executeUpdate() {
        return delegate.executeUpdate();
    }

    public <T> T unwrap(Class<T> type) {
        return type.cast(delegate);
    }

    public static final class ClientPreparedStatement implements Statement {
        private final String sql;

        ClientPreparedStatement(String sql) {
            this.sql = sql;
        }

        public String getPreparedSql() {
            return sql;
        }

        void setString(int index, String value) { }

        int executeUpdate() {
            return 1;
        }

        @Override public <T> T unwrap(Class<T> iface) { throw new UnsupportedOperationException(); }
        @Override public boolean isWrapperFor(Class<?> iface) { return false; }
        @Override public java.sql.ResultSet executeQuery(String sql) { throw new UnsupportedOperationException(); }
        @Override public boolean execute(String sql) { throw new UnsupportedOperationException(); }
        @Override public void close() { }
        @Override public int getMaxFieldSize() { return 0; }
        @Override public void setMaxFieldSize(int max) { }
        @Override public int getMaxRows() { return 0; }
        @Override public void setMaxRows(int max) { }
        @Override public void setEscapeProcessing(boolean enable) { }
        @Override public int getQueryTimeout() { return 0; }
        @Override public void setQueryTimeout(int seconds) { }
        @Override public void cancel() { }
        @Override public java.sql.SQLWarning getWarnings() { return null; }
        @Override public void clearWarnings() { }
        @Override public void setCursorName(String name) { }
        @Override public java.sql.ResultSet getResultSet() { return null; }
        @Override public int getUpdateCount() { return 0; }
        @Override public boolean getMoreResults() { return false; }
        @Override public void setFetchDirection(int direction) { }
        @Override public int getFetchDirection() { return 0; }
        @Override public void setFetchSize(int rows) { }
        @Override public int getFetchSize() { return 0; }
        @Override public int getResultSetConcurrency() { return 0; }
        @Override public int getResultSetType() { return 0; }
        @Override public void addBatch(String sql) { }
        @Override public void clearBatch() { }
        @Override public int[] executeBatch() { return new int[0]; }
        @Override public java.sql.Connection getConnection() { return null; }
        @Override public boolean getMoreResults(int current) { return false; }
        @Override public java.sql.ResultSet getGeneratedKeys() { return null; }
        @Override public int executeUpdate(String sql) { return 0; }
        @Override public int executeUpdate(String sql, int autoGeneratedKeys) { return 0; }
        @Override public int executeUpdate(String sql, int[] columnIndexes) { return 0; }
        @Override public int executeUpdate(String sql, String[] columnNames) { return 0; }
        @Override public boolean execute(String sql, int autoGeneratedKeys) { return false; }
        @Override public boolean execute(String sql, int[] columnIndexes) { return false; }
        @Override public boolean execute(String sql, String[] columnNames) { return false; }
        @Override public int getResultSetHoldability() { return 0; }
        @Override public boolean isClosed() { return false; }
        @Override public void setPoolable(boolean poolable) { }
        @Override public boolean isPoolable() { return false; }
        @Override public void closeOnCompletion() { }
        @Override public boolean isCloseOnCompletion() { return false; }
        @Override public long getLargeUpdateCount() { return 0; }
        @Override public void setLargeMaxRows(long max) { }
        @Override public long getLargeMaxRows() { return 0; }
        @Override public long[] executeLargeBatch() { return new long[0]; }
        @Override public long executeLargeUpdate(String sql) { return 0; }
        @Override public long executeLargeUpdate(String sql, int autoGeneratedKeys) { return 0; }
        @Override public long executeLargeUpdate(String sql, int[] columnIndexes) { return 0; }
        @Override public long executeLargeUpdate(String sql, String[] columnNames) { return 0; }
    }
}
