server.port=${SAMPLE_FULFILLMENT_PORT:19121}
spring.datasource.url=${SAMPLE_FULFILLMENT_MYSQL_URL}
spring.datasource.username=${SAMPLE_FULFILLMENT_MYSQL_USERNAME}
spring.datasource.password=${SAMPLE_FULFILLMENT_MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
dubbo.application.name=sample-fulfillment-service
dubbo.application.qos-enable=false
dubbo.registry.address=N/A
dubbo.protocol.name=dubbo
dubbo.protocol.port=${SAMPLE_FULFILLMENT_DUBBO_PORT:20880}
