#!/bin/sh
set -eu

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" <<SQL
CREATE USER IF NOT EXISTS '$MYSQL_APP_USER'@'%' IDENTIFIED BY '$MYSQL_APP_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER ON $MYSQL_DATABASE.* TO '$MYSQL_APP_USER'@'%';
CREATE USER IF NOT EXISTS '$MYSQL_ASSERTION_USER'@'%' IDENTIFIED BY '$MYSQL_ASSERTION_PASSWORD';
GRANT SELECT ON $MYSQL_DATABASE.* TO '$MYSQL_ASSERTION_USER'@'%';
FLUSH PRIVILEGES;
SQL
